# Site
name: "Le Blog des JegLain au Canada"
title: "Les JegLain au Canada"
description: "Une aventure en famille dans l'Ouest Canadien"
logo: 'assets/images/Canada_flag.jpg'
favicon: 'assets/images/Canada_flag.jpg'
baseurl: /
google_analytics: 'UA-154227687-1'
#disqus: 'demowebsite'
#mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: blog.jeglain@gmail.com

# Authors
authors:
  flelain:
    name: Flelain
    display_name: Flelain
    gravatar:
    avatar: 'assets/images/avatar_flo.jpg'
    email: blog.jeglain@gmail.com
    web:
    twitter:
    description: "An urban cyclist who rides with great delight as well in Rennes or Vancouver"
  lucien:
    name: Lulu
    display_name: Lulu    
    avatar: 'assets/images/avatar_lu.jpg'
    gravatar:
    email: blog.jeglain@gmail.com
    web: 
    twitter: 
    description: "jeune auteur de 10 ans, en train d'écrire son deuxième roman"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
